const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const source = fs.readFileSync(path.join(__dirname, "..", "codex-context-used-meter.js"), "utf8");
const between = (startMarker, endMarker) => {
  const start = source.indexOf(startMarker);
  const end = source.indexOf(endMarker, start + startMarker.length);
  assert.ok(start >= 0, `missing ${startMarker}`);
  assert.ok(end > start, `missing ${endMarker}`);
  return source.slice(start, end);
};
assert.match(source, /conversationGeneration: 0/);
assert.match(source, /activationEpoch: 0/);
assert.match(source, /authoritySnapshot: null/);
assert.match(source, /appSignalScopeGeneration: 0/);
assert.match(source, /appSignalCachedGeneration: 0/);
const activate = between("function activateConversationId(", "function retainConversationId(");
assert.match(activate, /state\.conversationGeneration \+= 1/);
assert.match(activate, /state\.activationEpoch \+= 1/);
assert.match(activate, /state\.lastReading = null/);
assert.match(activate, /state\.renderedContextReading = null/);
assert.match(activate, /clearAppSignalTransactionState\(\)/);
assert.doesNotMatch(activate, /readingsByConversationId\.get/);
const current = between("function isCurrentConversationTransaction(", "function getObjectConversationId(");
assert.match(current, /reading\.captureGeneration === state\.conversationGeneration/);
assert.match(current, /conversationIdsMatch\(reading\.conversationId, activeConversationId\)/);
const scope = between("function findAppSignalScope()", "function findLoadedAssetUrl(");
assert.match(scope, /state\.appSignalScopeGeneration === state\.conversationGeneration/);
assert.match(scope, /state\.appSignalScopeGeneration = state\.conversationGeneration/);
const scan = between("function scanAppSignalContextUsage(", "function collectContextUsageSampleConversationIds(");
assert.match(scan, /state\.appSignalCachedGeneration === state\.conversationGeneration/);
assert.match(scan, /result\.captureGeneration !== state\.conversationGeneration/);
assert.match(scan, /state\.appSignalCachedGeneration = state\.conversationGeneration/);
const detect = between("function detectReading()", "function rememberReading(");
assert.match(detect, /isCurrentConversationTransaction\(state\.lastReading, activeConversationId\)/);
assert.match(detect, /bindReadingToCurrentTransaction\([\s\S]*scanStatusReactContextUsage/);
assert.match(detect, /bindReadingToCurrentTransaction\([\s\S]*scanWindowForContextUsage/);
const remember = between("function rememberReading(", "function updateMeter()");
assert.match(remember, /if \(!isCurrentConversationTransaction\(reading, activeConversationId\)\) return/);
assert.match(remember, /state\.authoritySnapshot =/);
console.log("context conversation transaction contract: OK");
